name: Manual install

on:
  workflow_dispatch:
    inputs:
      run_tests:
        description: "Run tests?"
        required: true
        default: false
        type: boolean
  pull_request:
    types: 
      - opened
      - synchronize
      - reopened
    
jobs:
  install:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "16"

    - name: Install dependencies
      run: npm install

    - name: Run build
      run: npm run build
   
    - name: Run tests
      if: ${{ inputs.run_tests || github.event.pull_request}}
      run: npm test
